### ISSUE TITLE
Wikipedia as one of the useful tools ?

### ISSUE THREAD

**Issue by stouf** [Wizcorp/japanese-dev-lingo#8]
Do you think adding Wikipedia as one of the useful tools would be a good idea? I personally use it a lot to confirm a word and its context. It's also very useful when the Japanese page of an English article is available.

For example, say I'm looking for the Japanese for "Authentication". A search in [Jisho.org](http://jisho.org/) would give me [various results](http://jisho.org/search/Authentication), but I'm quite sure to get it right if I first go to the [Wikipedia article in English](https://en.wikipedia.org/wiki/Authentication) and then jump to [its equivalent in Japanese](https://ja.wikipedia.org/wiki/%E8%AA%8D%E8%A8%BC).

Do you think it would be worth mentioning it somewhere?

**Comment by ronkorving** [comment]
I think everyone on the planet by now knows *about* Wikipedia, so that may be a bit funky to add in that list as-is, I think. By the way, there is a better way to search jisho.org using hashtags. For example in the case of your "Authentication" example: http://jisho.org/search/Authentication%20%23comp will produce better results.

cc @beaucollins Do you have any input on this?

**Comment by stouf** [comment]
>  think everyone on the planet by now knows about Wikipedia

Hehe For sure ^^ I'm not sure if a lot of people think about using Wikipedia for translations though. But I agree it may don't have its place in here.

> there is a better way to search jisho.org using hashtags

Sweeeet! I didn't know about that `#compo` tag :D Thanks!

**Comment by ronkorving** [comment]
Up to you if you want to close this issue or leave it open for others to comment. In any case, thanks for thinking about ways to make this better :)

**Comment by stouf** [comment]
Let's close it :) Thanks for your feedback!
